#page title
page_title                                : Better Previews                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://chrome.google.com/webstore/detail/better-previews/mmmfofondapflhgbdidadejnechhjocm    # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://chrome.google.com/webstore/detail/better-previews/mmmfofondapflhgbdidadejnechhjocm    # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Better Previews                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A browser extension for previewing links and search results without opening new tabs.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Justice Ogbonna                              
your_link                                 : https://www.justiceo.com                     
your_city                                 : San Francisco                                
email_address                             : hello@justiceo.com
facebook_username                         : justice.ogb                                          
instagram_username                        : justice.ogbonna
twitter_username                          : justice_mode
github_username                           : justiceo
youtube_username                          : justiceo



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Voice is Faster
    description                           : “You can speak 110-150 words per min, as opposed to avg person's typing 38-40 wpm” - @purnavirji
    fontawesome_icon_name                 : rocket
    
  - title                                 : More ergnonomic
    description                           : “Repetitive motions like typing… that you do over and over can bring about carpal tunnel syndome” - WebMd.
    fontawesome_icon_name                 : couch

  - title                                 : Natural & Expressive
    description                           : Voice queries are longer and return more featured snippets than typed queries - Google Search.
    fontawesome_icon_name                 : seedling

  - title                                 : Privacy friendly
    description                           : All speech-recognition happens in your browser, we do not store or transfer any audio.
    fontawesome_icon_name                 : lock

  - title                                 : Highly accessible
    description                           : Using a keyboard with an unfamiliar layout/type? Not literate in English? Get onboard! 
    fontawesome_icon_name                 : universal-access
  
  - title                                 : Free forever
    description                           : The source code is open-source, [Github link](https://github.com/AudateApp/voice-search-extension). No ads, no sign-ups, no bs.
    fontawesome_icon_name                 : gift

  - title                                 : Popular search engines
    description                           : You can choose from Google to Bing, Baidu, Yandex, Yahoo, DuckDuckGo and Ecosia.
    fontawesome_icon_name                 : fire

  - title                                 : Over 300 locales supported
    description                           : For each language, you can choose a country-specific dialect for high-accuracy recognition.
    fontawesome_icon_name                 : globe

  - title                                 : State of the art AI
    description                           : Automatically detects an ignores music, noise. Detects active mic and when you stop speaking.
    fontawesome_icon_name                 : robot

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
